### PR TITLE
fixed

### PR DESCRIPTION
**Pull request by mametur**
related #1

### CODE REVIEW

**Comment by mametur** [comment]
#1 merged

**Comment by snicoll** [comment]
"fixed" does not convey a lot of information. You'd provide a description of what the intent is. While the issue describes the task and some background information, the PR usually describe a bit more in technical term what was fixed.

**Comment by mametur** [comment]
@snicoll  for issues, ->`the background color fixed #3` is the correct message?
 for PR -> `the background color changes  RGB to HEX` is the correct message?

**Comment by snicoll** [comment]
I am not sure I understood the question.

"the background color fixed #3" does not sound great I am afraid. You don't need to put everything in the title. Since you have an issue reference there, did you mean PR title or something?


Commit message should be imperative, `Change background color to HEX` or something would do based the info you've provided.

**Comment by mametur** [comment]
@snicoll I misunderstood, I  thought that  my commit was not clear but Now I see that title for issues and PR should  be more clear  :cry:  I am going to hit my head to the wall  :hear_no_evil:

**Pull request merged**
